# Generated by Django 3.0.6 on 2020-06-02 10:26

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200601_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=True, populate_from=models.CharField(blank=True, max_length=250, verbose_name='Title')),
        ),
    ]
