# Generated by Django 3.0.6 on 2020-06-03 05:36

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200602_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=True, populate_from=models.CharField(blank=True, max_length=250, verbose_name='Title'), unique=True),
        ),
    ]
